# Engineering Maths 8.1 - 2020

## Vector Algebra Using Python


* As with all python workbooks, the first thing we have to do is import all the required.



* The main library we need for this workbook is the __Num__erical __Py__thon (__numpy__) library.


* To run the code cell below, click on thes cell and press __SHIFT+ENTER.__

In [1]:
import numpy as np # np is an abbraviation we give to the library, 
                   # so we don't have to type numpy every time we want to 
                   # call a function from the library 

# Creating 2D vectors with Python


* As we saw in lectures, a 2D vector $\vec{v}=v_{1}\hat{\imath}+v_{2}\hat{\jmath}$ can be written as an __array__ of the form 

$$\vec{v}=\begin{bmatrix}v_{1}\\ v_{2}\end{bmatrix} \text{ or }\vec{v}=\begin{bmatrix}v_1&v_{2}\end{bmatrix}.$$


* This vector can be created numericall using the numpy function __np.array([v1,v2])__. We need the __np__ out in front to indicate the __array([,])__ function comes from the __numpy__ library.


## Example 1: 

* Use __np.array([])__ to create numercal vecotrs for

$$\vec{A}=-4.2\hat{\imath}+6.7\hat{\jmath}\quad\vec{B}=3.8\hat{\imath}+6.1\hat{\jmath}\quad 
\vec{C}=1.7\hat{\imath}-8.4\hat{\jmath}.$$

In [2]:
A=np.array([-4.2,6.7]) # Be carfule with brackets when using array, note the double brackets np.array([,])
A

array([-4.2,  6.7])

## A function for creating vectors

* If we need the create a lot of vectors, we would like to avoid writing our __np.array([])__ for each one.


* We can make things a litle more efficient by creating a function that will create a 2D vector with components $v_1$ and $v_2$.


* We do this in the cell below:

In [3]:
def V2(x1,x2):# x1 & x2 are place holders for the compenents we want to create. We can replace these with anything we want.
    return np.array([x1,x2]) # We name the function V2() to indicate it is a vector in 2D.

In [4]:
B=V2(3.8,6.1)
B

array([3.8, 6.1])

In [5]:
C=V2(1.7,-8.4)
C

array([ 1.7, -8.4])

### Vector algebra in 2D.


* Now that we have created numerical cetors in 2D, we can perfom all the familiar operatins of vector algebra, like addition, subtraction, scalar multiplication.


* For now, we will do the following:

__1.__ Find $$3.5\vec{A}-7.8\vec{B}$$

__2.__ Find $$4.2\vec{A}+4.8\vec{C}$$

__3.__ Find $$-1.9\vec{B}+7.8\vec{C}$$

__4.__ Find $$2.5\vec{A}-4.3\vec{B}+6.2\vec{C}$$


#### Solution:

 * Finding these vectors is almost identical to the way you would carry it out using pen & paper. 
 
 
 * The only the we must be __careful__ about is using __*__  everytime we have multiplication between a scalar and a vector. 

In [6]:
3.5*A-7.8*B # Notice the * for multiplication each time!!

array([-44.34, -24.13])

In [7]:
-1.9*B+7.8*C

array([  6.04, -77.11])

In [8]:
2.5*A-4.3*B+6.2*C

array([-16.3 , -61.56])

## Exercise 1


__1.__ Create numerical arays to represent the vectors 

$$\vec{U}=-1.4\hat{\imath}+4.2\hat{\jmath},\quad \vec{V}=7.6\hat{\imath}+5.5\hat{\jmath}, \quad \vec{W}=2.7\hat{\imath}-3.2\hat{\jmath},\quad \vec{X}=-3.4\hat{\imath}-5.2\hat{\jmath}.$$


__2.__ Using these numerical vectors, find each of the following:
    
__2 (i)__ $$4.5\vec{U}-7.3\vec{W}$$


__2 (ii)__ $$-1.5\vec{W}+3.3\vec{X}$$


__2 (iii)__ $$-3.1\vec{U}-7.3\vec{W}-8.9\vec{V}$$


__2 (iv)__ $$425\vec{V}-6.4\vec{W}+11.2\vec{X}$$


__2 (v)__ $$6.5\vec{X}-5.1\vec{W}+3.4\vec{V}+6.6\vec{U}$$

# The Dot Product

* We have seen during lectures that the dot product of the vectors 
$\vec{u}=u_{1}\hat{\imath}+u_2\hat{\jmath}$  and 
$\vec{u}=u_{1}\hat{\imath}+u_2\hat{\jmath}$  
is given by:

$$
\vec{u}\cdot \vec{v}=\left(u_{1}\hat{\imath}+u_{2}\hat{\jmath}\right)\cdot\left(v_{1}\hat{\imath}+v_2\hat{\jmath}\right)=u_1v_2+u_2v_2.
$$


* When we multiply two arrays __of the same length__ in Python, it perfoms this operation __entrywise__, i.e. the first entry is multiplied by the first entry and so on...


*italicized text*

## Example 2

* Multiply the two arrays 

$$P=[1,2]\quad Q=[3,4]$$

* We use such simple numbers just to make it easier to see.

In [9]:
P=V2(1,2)
Q=V2(3,4)
P,Q

(array([1, 2]), array([3, 4]))

In [10]:
P*Q # We still need * for multiplication, even with arrays!!

array([3, 8])

* So we see that  **P\*Q=[1,2]\*[3,4]=[1\*3,2\*4]=[3,8]**, so the multiplication is performd entry by entry.



* Going back to vectors, we see that the dot product of the vectors 
$$\vec{P}=1\hat{\imath}+2\hat{\jmath}\text{ and }\vec{Q}=3\hat{\imath}+4\hat{\jmath}\\$$
is given by
$$\\ \vec{P}\cdot\vec{Q}=(1)(3)+(2)(4)=3+8=11.$$



* Hence, just by multiplying the arrays __P__ and __Q__, we are half way to the dot product, all we have to do is add up the entries of the array __P*Q__ to get the dot product.


* This can be done with the function __sum()__, which just adds up all the entries of an array (of any length).

In [11]:
sum(P*Q)

11

## A function for the dot product:

* We can even create another function to automate this for us

In [12]:
def Dot(U,V):
  return sum(U*V) # U & V here are just place holder names, not actual arrays   

* This function can be used for arrays of any length, so it can be used to take a dot product in 2D, 3D, 4D,...

## Example 3

* Find the dot product of the vectors

$$1.2\vec{A}-4.5\vec{C} \text{ and }4.3\vec{B}+1.3\vec{A}$$


### Solution


* In this case, we do not need to even find the individual vectors $1.2\vec{A}$ etc, and since we have already defined arrays __A__, __B__ and __C__ to represent $\vec{A}$, $\vec{B}$ and $\vec{C}$, most of the work is already done!!


* All we have to do is:

In [14]:
Dot(1.2*A-4.5*C, 4.3*B+1.3*A)

1463.5824

# The norm of a vector

* Given the vector $\vec{u}=u_1\hat{\imath}+u_2\hat{\jmath}$, we see that its norm can be wrriten as

$$\left\Vert\vec{u}\right\Vert=\sqrt{u_1^2+u_2^2}=\sqrt{\vec{u}\cdot\vec{u}}.$$


* So now we can use this to create a function to find the __norm__ of a vector:


In [16]:
def norm(U):
  return np.sqrt(Dot(U,U))

* Here we have used the __Dot(,)__ function we created earlier to take the dot product of the array __U__ with itself.


* We also use the __numpy__ function __sqrt()__, the __np__ in front is to indicate that it is called from the __numpy__ library.


## Example 3

* Find the norm  of each of the vectors

$$1.2\vec{A}-4.5\vec{C} \text{ and }4.3\vec{B}+1.3\vec{A}$$


### Solution, again, most of the work is done for us, so all we have to do is:

In [17]:
norm(1.2*A-4.5*C)

47.564079934337

In [18]:
norm(4.3*B+1.3*A)

36.59478104866867

## Exercise 2

* Find the norm of __all 9__ vectors in __Exercise 1__.